<a href="https://colab.research.google.com/github/HUANGR2000/Tensorflow_teaching/blob/main/Copy_of_00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook, we're going to cover some of the most fundamental concepsts of tensors using TensorFlow

More specifically, we're going to cover :

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your Python function)
* Using GPUs with Tensorflow(or TPUs)
* Exercises to try for yourself!

In [ ]:
##Introduction to Tensors
import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
#Let's create a tensor

tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor


NameError: ignored

In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar #数量 numpy处理大量数据矩阵

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#create two radom (but the same) tensor
import tensorflow as tf
random_1 = tf.random.Generator.from_seed(7) #set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3,2))

#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

shuffle the order of elements in atensor

In [ ]:
#shuttle a tensor (valuable for when you want to shuffle your dataq so the inherent)
import tensorflow as tf
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
not_shuffled.ndim

#shuttle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# Check the number of dimensions of a tensor( ndim stands for number of dimensions)

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector#矢量

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimensionh of our vector
vector.ndim#空间维数

1

In [ ]:
# Create a matrix (has more than 1 dimension)

matrix = tf.constant([[10,7],[7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.], [3.,2.],[8.,9.]], dtype=tf.float16) #specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number dimension of another_matrix?

another_matrix.ndim

NameError: ignored

In [ ]:
tensor.ndim

4

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of number (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tenson is a vector)

tensorflow.python.ops.variables.Variable

In [ ]:
#Create the same tesnor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

NameError: ignored